### PR TITLE
feat(simpleList): rename isCurrent to isActive

### LINKED ISSUE #133: SimpleList: Replace prop isCurrent with isActive
Issue:  https://github.com/patternfly/patternfly-react/pull/8132

`isCurrent` is deprecated and has been replaced with `isActive` - functionality remains the same, only name has changed.

_Required actions:_
1. Build codemod
2. Build test
3. Update readme with description & example

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
Closes #133

### CODE REVIEW

**Review by gitdallas — APPROVED** [review]
Looks good. It's done the same way in several areas but I'm wondering if we should provide a default message for renameProp. Otherwise only use renameProps (even if only a single rename in it like is done in `chartVoronoiContainer-remove-allowTooltip`) as it already provides default messages. Would remove duplicate or inconsistent verbiage.

Many of the places where singular `renameProp` is used is to provide a custom message on purpose - see `accordion-remove-noBoxShadow` for example. Might make sense to allow a `message` prop (even in `renameProps`) and allow that to override the default if necessary... but always provide the default.

This could all be a separate story though.

**Comment by wise-king-sullyman** [comment]
@gitdallas agree, I think it would be beneficial to do one of those. Not sure what the better approach would be off the top of my head though.

Along a similar line of thinking, while I wrote this I debated throwing together a generator or something to do the standard 1 component, 1 prop name being changed codemod like we have here. I figure this format will be pretty common. WDYT?

**Comment by gitdallas** [comment]
@wise-king-sullyman if i understand you correctly, that already exists. https://github.com/patternfly/pf-codemods/blob/master/generate.js

**Comment by wise-king-sullyman** [comment]
@gitdallas that's similar, but not as specific. I whipped together a version of what I was thinking of here: #190 

It would be specifically for these basic single component 1:1 prop replacements specifically, which seem somewhat common. Though maybe it's a bit *too* specific to be all that useful.

**Review by thatblindgeye — COMMENTED** [review]
Just some conflicts to resolve but otherwise looks good! Would be worth placing the section in the README alphabetically as part of resolving those

**Review by thatblindgeye — APPROVED** [review]

**Pull request merged**
