### PR TITLE
feat(InvalidObject): rename props

### LINKED ISSUE #666: [component-groups | InvalidObject] - Rename props
Follow up to breaking change [PR](https://github.com/patternfly/react-component-groups/pull/145)

We've renamed some ErrorState props to comply with its base component - PF EmptyState

rename
`invalidObjectTitleText` to `titleText`
`invalidObjectBodyText` to `bodyText`

Example:
```
<InvalidObject invalidObjectTitleText='Sample title' invalidObjectBodyText='Sample description' />
```
becomes
```
<InvalidObject titleText='Sample title' bodyText='Sample description' />
```
Required actions:
- Build codemod
- Build test
- Update readme with description & example

### PR DESCRIPTION
**Pull request by adamviktora**
Closes #666

### CODE REVIEW

**Review by wise-king-sullyman — CHANGES_REQUESTED** [review]
It looks like per the issue this should also rename `defaultErrorDescription` to `defaultBodyText` shouldn't it?

**Comment by adamviktora** [comment]
> It looks like per the issue this should also rename defaultErrorDescription to defaultBodyText shouldn't it?

About this, I was checking the [PR changes](https://github.com/patternfly/react-component-groups/pull/145/files#diff-cdcab91792a828b2d103b626115b6963dc911a2b88f98c039af9f2cb1c328434), and there was no `defaultErrorDescription` prop in `InvalidObject` component. It seems to me like the issue description was copied out from the ErrorState issue, where this prop occurs.

**Comment by wise-king-sullyman** [comment]
@fhlavac can you confirm that we only need to rename the `invalidObjectTitleText` and `invalidObjectBodyText` props for this component?

**Review by wise-king-sullyman — APPROVED** [review]
Assuming that comes back as a yes this looks great!

**Comment by fhlavac** [comment]
@wise-king-sullyman @adamviktora yeah, only `invalidObjectTitleText` and `invalidObjectBodyText` should be renamed. Sorry, I somehow missed that when creating all the tickets. Thank you 🙂

**Review by thatblindgeye — APPROVED** [review]

**Pull request merged**
